### PR TITLE
This is my initials of my portfolio

### PR DESCRIPTION
**Pull request by sayan6823**
@ShreyaDhir @SubhayanDas08 

HTML AND CSS HAS BEEN USED FOR NOW

### CODE REVIEW

**Review by nishant-giri — APPROVED** [review]
Thank you, @chiku6823 for your contribution.

**Comment by sayan6823** [comment]
hi i have some doubts... i have edited the education.html recently..but
cannot push it..plz check why it is showing this error


"Permission to MSCKIIT/MSCxPortfolio.git denied to chiku6823."

Like this...

Is there any solution?

I am a beginner so i  cnt understand

**Comment by nishant-giri** [comment]
@chiku6823, you need to pull the origin branch, so that you are able to merge new changes from our main branch to your branch.

**Comment by sayan6823** [comment]
bhaiya i havent recieved the workshop completion certificate yet???😅😅

**Pull request merged**
